In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("matchStats/csv/fotmob_match_stats.csv")
df.head()

,matchId,matchRound,homeTeamName,homeTeamid,awayTeamName,awayTeamid,home_goals,away_goals,ball_possession_home,ball_possession_away,...,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away,yellow_cards_home,yellow_cards_away,red_cards_home,red_cards_away
0,4825019,1,Birmingham City,8658,Ipswich Town,9902,1,1,51,49,...,40 (63%),23 (37%),12 (38%),20 (63%),2 (67%),5 (38%),2,3,0,0
1,4825020,1,Charlton Athletic,8451,Watford,9817,1,0,42,58,...,38 (63%),22 (37%),12 (28%),31 (72%),7 (70%),6 (55%),1,2,0,0
2,4825021,1,Coventry City,8669,Hull City,8667,0,0,58,42,...,22 (41%),32 (59%),18 (51%),17 (49%),4 (29%),3 (38%),3,3,0,0
3,4825022,1,Southampton,8466,Wrexham,9841,2,1,75,25,...,32 (48%),34 (52%),19 (61%),12 (39%),8 (53%),4 (44%),2,2,0,0
4,4825023,1,Middlesbrough,8549,Swansea City,10003,1,0,54,46,...,37 (41%),53 (59%),18 (51%),17 (49%),7 (32%),9 (50%),2,5,0,0